# __  __                __  __       _                            __ _       
#|  \/  | _____   _____|  \/  | ___ | |__  ___    ___ ___  _ __  / _(_) __ _ 
#| |\/| |/ _ \ \ / / _ \ |\/| |/ _ \| '_ \/ __|  / __/ _ \| '_ \| |_| |/ _` |
#| |  | | (_) \ V /  __/ |  | | (_) | |_) \__ \ | (_| (_) | | | |  _| | (_| |
#|_|  |_|\___/ \_/ \___|_|  |_|\___/|_.__/|___/  \___\___/|_| |_|_| |_|\__, |
#                                                                      |___/

#DO NOT TOUCH 
config-version: 1


#message
Message:
  waiting: Waiting for you to kill the mob that you want to move.
  alreadydone: You already picked up a mob.
  fewargs: Too few Arguments.
  nomob: You didn't picked up any mob.
  spawningmob: Spawning your mob.
  pickedup: I picked up the mob.


#mobs that the players are allowed to move
mobwhitelist:
  - WOLF
  - HORSE