name: MoveMobs
version: 1.0
main: de.darcade.movemobs.movemobs
author: Darcade
website: http://darcade.de/
commands:
     movemob:
          description: waits for a player to kill a mob and them gives him an egg
          usage: /<command>
          permission: movemob